name: build-and-deploy
on: 
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build-eleventy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.3.0'
      - name: Clean install dependencies
        run: npm ci
      - name: Clean eleventy build folder
        run: npm run clean
      - name: Build eleventy site
        run: npm run build      
  deploy-aws-cdk:
    needs: build-eleventy-site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.3.0'
      - run: cdk deploy --all
