name: build-and-deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  cache_node_modules:
    name: Cache node_modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.3.0"
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - run: npm ci
  build_eleventy_site:
    name: Build 11ty site
    runs-on: ubuntu-latest
    needs: cache_node_modules
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.3.0"
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Clean install dependencies
        run: npm ci
      - name: Clean eleventy build folder
        run: npm run clean
      - name: Build eleventy site
        run: npm run build
  deploy-aws-cdk:
    # site must be build before running deployment
    needs: [cache_node_modules, build_eleventy_site]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.3.0"
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Clean install dependencies
        run: npm ci
      - run: cdk deploy --all
