name: test-workflow
on:
  workflow_dispatch:
env:
  MY_SECRET: ${{ secrets.TEST_SECRET }}
jobs:
  test_job:
    name: Testing some things
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.3.0"
      - name: test secret value
        if:  env.MY_SECRET == 'test123'
        run: echo "env.MY_SECRET == 'test123'"
      - name: put secret in file
        run: |
          touch temp.txt
          echo MY_SECRET_1="https://xxx.execute-api.us-west-2.amazonaws.com" >> temp.txt
          echo MYSECRET2=${{ secrets.TEST_SECRET }} >> temp.txt
          echo MYSECRET3=${{ env.MY_SECRET }} >> temp.txt
          cat temp.txt
