name: test-workflow
on:
  workflow_dispatch:
env:
  MY_SECRET: ${{ secrets.TEST_SECRET }}
jobs:
  test_job:
    name: Testing some things
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.3.0"
      - name: List secrets
        run: |
          echo "TEST_SECRET:\ ${{ secrets.TEST_SECRET }}"
          echo "MY_SECRET:\ ${{ secrets.MY_SECRET }}"
      - name: Add mask to environment secrets
        run: |
          echo "::add-mask::${{ secrets.TEST_SECRET }}" 
          echo "::add-mask::${{ secrets.MY_SECRET }}" 
      - name: Try listing secret again
        run: |
          echo "TEST_SECRET:\ ${{ secrets.TEST_SECRET }}"
          echo "MY_SECRET:\ ${{ secrets.MY_SECRET }}"