name: test-workflow
on:
  workflow_dispatch:
env:
  MY_SECRET: ${{ secrets.TEST_SECRET }}
jobs:
  test_job:
    name: Testing some things
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.3.0"
      - name: test
        if:  env.MY_SECRET == 'This is a secret!'
        run: echo "env.MY_SECRET == 'This is a secret!'"
